---
title: "SIMPLEX + LINCX:"
output: html_document
editor_options: 
  chunk_output_type: console
---

## LINCX: Linking Network structure and species CoeXistence.
## SIMPLEX: Simple models that capture the complexity of multi-species coexistence 

**Explora ciencia projects** CGL2014-61590-EXP and CGL2017-92436-EXP.  
**Researchers: Ignasi Bartomeus and Oscar Godoy**    

This two linked projects explore how we can add multitrophic complexity to species coexistence models.   

**Lincx** put forward the fundational theoretical work (Godoy et al 2019), and tested the models with experimental (Bartomeus et al. 2021) and observational data (Lanuza et al 2019).  

Papers:   

- Godoy, O., Bartomeus, I., Rohr, R. P., & Saavedra, S. (2018). Towards the integration of niche and network theories. Trends in Ecology & Evolution, 33(4), 287-300.  
- Lanuza, J. B., Bartomeus, I., & Godoy, O. (2018). Opposing effects of floral visitors and soil conditions on the determinants of competitive outcomes maintain species diversity in heterogeneous landscapes. Ecology Letters, 21(6), 865-874.   
- Bartomeus, I., & Godoy, O. (2018). Biotic controls of plant coexistence. Journal of Ecology, 106(5), 1767-1772.  
- Bartomeus, I., Saavedra, S., Rohr, R.P. and Godoy, O., 2021. Experimental evidence of the importance of multitrophic structure for species persistence. Proceedings of the National Academy of Sciences, 118(12).
- Busche, Bartomeus, Godoy. Higher Order Interactions. In Prep.   

**SIMPLEX** tries to operationalyze those models (Martin et al 2021), make them useful (Garcia-Callejas et al 2020), and predictive (Civantos et al 2021).  

Papers:

- García‐Callejas, D., Godoy, O., & Bartomeus, I. cxr: A toolbox for modelling species coexistence in R. Methods in Ecology and Evolution. In press.  
R Package: https://github.com/RadicalCommEcol/cxr  
- Civantos, I., García-Algarra, J., García-Callejas, D., Galeano, J., Godoy, O. and Bartomeus, I., 2021. Fine scale prediction of ecological community composition using a two-step sequential machine learning ensemble. bioRxiv. 
- Garcia-Callejas, Hurtado, Godoy, Bartomeus. The multilayer structure of plant-pollinator-herbivore networks. In prep.  
- Martyn, T.E., Stouffer, D.B., Godoy, O., Bartomeus, I., Pastore, A.I. and Mayfield, M.M., 2021. Identifying “Useful” Fitness Models: Balancing the Benefits of Added Complexity with Realistic Data Requirements in Models of Individual Plant Fitness. The American Naturalist, 197(4), pp.415-433.





